In [ ]:
# 参考官方文档：https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
from __future__ import print_function
import torch

x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 1.0842e-19, 0.0000e+00],
        [1.0842e-19, 1.1210e-44, -0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [2]:
x = torch.rand(5,3)
print(x)

tensor([[0.5928, 0.2400, 0.3196],
        [0.9030, 0.0830, 0.7755],
        [0.2942, 0.3306, 0.9808],
        [0.6535, 0.5546, 0.5774],
        [0.0322, 0.4911, 0.3170]])


In [3]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.4703, 0.1611, 0.4310],
        [0.2767, 0.4998, 0.9199],
        [0.8331, 0.5240, 0.2218],
        [0.2471, 0.8965, 0.6419],
        [0.4528, 0.0153, 0.1898]])


In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
y = torch.rand(5, 3)
print(x+y)

tensor([[0.7343, 1.0458, 0.9299],
        [0.2876, 0.8087, 1.5974],
        [1.3278, 0.6815, 0.6203],
        [0.6891, 1.1373, 1.0983],
        [0.7489, 0.9168, 1.0853]])


In [8]:
print(torch.add(x,y))

tensor([[0.7343, 1.0458, 0.9299],
        [0.2876, 0.8087, 1.5974],
        [1.3278, 0.6815, 0.6203],
        [0.6891, 1.1373, 1.0983],
        [0.7489, 0.9168, 1.0853]])


In [9]:
result = torch.empty(5, 3)
torch.add(x,y,out=result)
print(result)

tensor([[0.7343, 1.0458, 0.9299],
        [0.2876, 0.8087, 1.5974],
        [1.3278, 0.6815, 0.6203],
        [0.6891, 1.1373, 1.0983],
        [0.7489, 0.9168, 1.0853]])


In [10]:
y.add_(x)   
#Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
y.add(x)
print(y)

tensor([[0.7343, 1.0458, 0.9299],
        [0.2876, 0.8087, 1.5974],
        [1.3278, 0.6815, 0.6203],
        [0.6891, 1.1373, 1.0983],
        [0.7489, 0.9168, 1.0853]])


In [12]:
print(x)

print(x[:,-1])   # 取最后一列的元素

tensor([[0.4703, 0.1611, 0.4310],
        [0.2767, 0.4998, 0.9199],
        [0.8331, 0.5240, 0.2218],
        [0.2471, 0.8965, 0.6419],
        [0.4528, 0.0153, 0.1898]])
tensor([0.4310, 0.9199, 0.2218, 0.6419, 0.1898])


In [13]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 7)
y = x.view(28)
z = x.view(-1,2)    # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 7]) torch.Size([28]) torch.Size([14, 2])


In [14]:
# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())


tensor([0.2867])
0.28670191764831543


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
# converting torch tensor to a numpy array
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
# The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
